# version: "3.9"

services:
  app:
    build:
      context: .
      # dockerfile: Dockerfile
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    # image: your-app-image:latest
    container_name: receipe_app_container
    # environment:
    #   - ENV_VAR1=value1
    #   - ENV_VAR2=value2
    # networks:
    #   - app_network