# version: "3.9"

services:
  app:
    build:
      context: .
      # dockerfile: Dockerfile
      args:
        - DEV=true
    image: receipe_app
    ports:
      - "8000:8000"
    # networks:
    #   - backend
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    # image: your-app-image:latest
    container_name: receipe_app_con
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
    depends_on:
      - db
    restart: always
  

  db:
    image: postgres:14-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme
    restart: always



volumes:
  dev-db-data:

  # networks:
  #   backend:
  #     driver: bridge