---

name: CI Checks
on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2

      # - name: Set up Python
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: '3.12'
          
      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install flake8

      - name: Run linter
        run: docker compose run --rm app sh -c "flake8 ."
        # run: flake8 .

      - name: Run Test
        run: docker compose run --rm app sh -c "python manage.py test"

      # - name : test
      #   run: |
      #     docker build --build-arg DEV=true -t your-app-image:latest .
      #     docker run --rm your-app-image:latest sh -c "python manage.py test"

  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v1

  #     - name: Build and push Docker image
  #       uses: docker/build-push-action@v2
  #       with:
  #         context: .
  #         push: false
  #         tags: your-app-image:latest
  #         build-args: |
  #           DEV=true

  #     - name: Run tests
  #       run: |
  #         docker run --rm your-app-image:latest sh -c "python manage.py test"
